### ISSUE TITLE
[security issue]  Switch to using `random.SystemRandom`, else passwords might be guessable

### ISSUE THREAD

**Issue by cipriancraciun** [dragosion/GenPw2Clipboard#1]
At the moment you are using `random.randint` that, according to the Python documentation it is unsuitable for such purposes you are using:
> However, being completely deterministic, it is not suitable for all purposes, and is completely unsuitable for cryptographic purposes.
> https://docs.python.org/3/library/random.html

Moreover I think older Python used to seed the generator with the current timestamp.  Thus if one knows the approximate moment a password was generated, one can generate a much smaller list of possible candidates.

**Comment by dragosion** [comment]
It's used only for the lenght of the password but I'll look into it. 
It should be easy to change.
Rest uses the secrets.
Thank you for sending the issue!

**Comment by cipriancraciun** [comment]
Yes, you are right, the `randint` is used only for the length.  (I didn't pay much anttention to the algorithm, I just saw the usage of the `random` module, and I've seen quite a few tools that used it instead of a secure generator.)

(Also interesting, I didn't knew about the `secrets` built in module.  Too bad it's not also available for Python 2.)

**Comment by dragosion** [comment]
Removed random anyway, using secrets for the length too. A bit too much but can't hurt it.
Thanks again!
